development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

log_db:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: log_db
  pool: 5
  username: root
  password: ""
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
